// =============================================================
// VOICE CLIPS — per-word pronunciation audio (generated by core/tts.js,
// currently used by templates/anagram/anagram-editor.js) stored as ITS
// OWN Firestore document, one per clip — NOT embedded inside the
// activity's content.items[] — because an Anagram activity can hold up
// to 100 words, and a single generated clip already runs ~50-150KB; a
// handful of clips embedded directly would blow past Firestore's 1MiB-
// per-document ceiling (the whole activity — and later, the whole
// assignment snapshot, see core/assignments.js's snapshotOf() — is ONE
// document).
//
// Lives in a TOP-LEVEL `voiceClips/{clipId}` collection (NOT nested
// under users/{uid}), with PUBLIC READ — same trust model as
// `assignments/{code}`: the id is a random Firestore auto-id (practically
// unguessable), and public-read-by-id is what lets a STUDENT's play.js
// (which never signs in) play a clip whose id merely rides along inside
// content.items[].voice when a teacher shares an assignment — no extra
// copy step needed at share time, because assignments.js's snapshotOf()
// already carries `content` through byte-for-byte.
//
// Firestore rule to add (docs/08-FIREBASE-SETUP.md), teacher pastes into
// the Firebase console same as the existing rules:
//   match /voiceClips/{clipId} {
//     allow read: if true;
//     allow write: if isTeacher();
//   }
//
// Regenerating a word's voice REUSES its existing clip id (pass `id`) —
// keeps one doc per item instead of leaving orphans behind every time a
// teacher tries a different Kokoro voice on the same word. Removing a
// voice (the trash icon in the editor) does delete its doc; an orphan can
// still occur if a teacher deletes/edits the WORD after generating a clip
// for it — not cleaned up automatically (single-teacher scale, a handful
// of stray ~100KB docs is not worth a GC pass over the whole library).
// =============================================================

import { db, fs, currentUser } from "./firebase.js";

function now() { return Date.now(); }

function requireSignedIn(user) {
  if (!user) { const e = new Error("Please sign in first."); e.code = "aw/signed-out"; throw e; }
}

// Create (id omitted) or overwrite (id given) a clip. Returns the clip id.
export async function saveVoiceClip({ id, text, voiceId, audioDataUrl }) {
  const user = await currentUser();
  requireSignedIn(user);
  const [d, { doc, collection, setDoc }] = await Promise.all([db(), fs()]);
  const ref = id ? doc(d, "voiceClips", id) : doc(collection(d, "voiceClips"));
  await setDoc(ref, { text, voiceId, audio: audioDataUrl, createdAt: now(), ownerUid: user.uid });
  return ref.id;
}

// Public read — no sign-in required, so a student's play.js can fetch a
// clip referenced inside an assignment it was handed a link to.
export async function getVoiceClip(id) {
  if (!id) return null;
  const [d, { doc, getDoc }] = await Promise.all([db(), fs()]);
  const snap = await getDoc(doc(d, "voiceClips", id));
  return snap.exists() ? snap.data() : null;
}

export async function deleteVoiceClip(id) {
  if (!id) return;
  const user = await currentUser();
  requireSignedIn(user);
  const [d, { doc, deleteDoc }] = await Promise.all([db(), fs()]);
  await deleteDoc(doc(d, "voiceClips", id));
}
